# Generated by Django 4.2.23 on 2025-08-14 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="ContactModel", new_name="Contact",),
    ]
