# Generated by Django 4.2.23 on 2025-08-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_rename_contactmodel_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="contact",
            name="picture",
            field=models.ImageField(blank=True, upload_to="pictures/%Y/%m/"),
        ),
        migrations.AddField(
            model_name="contact", name="show", field=models.BooleanField(default=True),
        ),
    ]
